### ISSUE TITLE
Add youthostel to accomodation and groceries map

### ISSUE THREAD

**Issue by meiersi-da** [wereHamster/zurihac-2017-website#10]
https://www.google.com/maps/d/u/0/viewer?mid=1OmDEXl-VKylIyv2Or-yH0nqah38&ll=47.21833480000003%2C8.836499000000003&z=17

**Comment by meiersi-da** [comment]
I've tried to add this, but I don't think I have edit rights on the map. @wereHamster could you add it, as you likely have edit rights.

**Comment by wereHamster** [comment]
I added the youth hostel, and gave you and @jaspervdj edit rights to the map.
