### ISSUE TITLE
Nice register URL

### ISSUE THREAD

**Issue by jaspervdj** [wereHamster/zurihac-2017-website#3]
@wereHamster Is it possible to set up a nicer register URL that redirects to the google form?

This is the link: (see google doc)

I am thinking of either `zurihac.info/register` or `register.zurihac.info`.  I'm not sure how the web framework works (and maybe there's server in front of it which handles that?).  As a last resort we could always just have `zurihac.info/static/register.html` which has a `<meta>` tag like:

```
 <html>    
  <head>      
    <meta http-equiv="refresh" content="0;URL='http://...'" />    
  </head>    
  <body> 
    ...
  </body>  
</html>     
```

**Comment by wereHamster** [comment]
https://zurihac.info/register -> implemented as a 307 redirect in nginx
