### ISSUE TITLE
Update header image from 2017 to 2018

### ISSUE THREAD

**Issue by jaspervdj** [wereHamster/zurihac-2017-website#49]
I can't do this since I don't know the font (and it's quite nice)

**Comment by jaspervdj** [comment]
Sorry to bother you again @wereHamster, but we'd also need the dates to read 8-10 June.  After that I think we're good to do the announcement.  :-)

**Comment by wereHamster** [comment]
5669d9adcddb65a3f17dbd2c22e55cccdb6aa012 should be live in a few minutes.

**Comment by jaspervdj** [comment]
Thanks again!!  Much appreciated
