### ISSUE TITLE
Style issue in navigation header

### ISSUE THREAD

**Issue by jaspervdj** [wereHamster/zurihac-2017-website#53]
The "Contact" button is displayed below the navigation header and only appears on hover

![zurihac](https://user-images.githubusercontent.com/95501/34121750-5d051d38-e42a-11e7-9e94-6ee73ba7616e.png)

**Comment by wereHamster** [comment]
I'll need to redo the whole header+navigation, the current structure doesn't work. I fixed it for the time being.
